@startuml
participant App as App
participant SDK as SDK
participant "SmartyzeDetect License API" as SDAPI

App -> SDK : getStatus()
SDK --> App : ActivationChallenge
App -> SDAPI : GetLicense(ActivationChallenge)
SDAPI --> App : License
App -> SDK : init(License)
SDK -> SDAPI : VerifyLicense(License)
SDAPI --> SDK : Success
SDK --> App : Success
@enduml

